Add hardware requirements in validator node
ripple/opensource.ripple.com pull request #48
Opened 2023-08-15 06:59 UTC by AdriaCarrera

2023-08-31 22:39 UTC, mDuo13 requested changes
It appears you've run some kind of automatic formatting script on the repo and proposed the changes. Many of the resulting changes are unwanted. Please trim this PR back to just the substantive changes (hardware requirements to validator node) and not all the other stuff.

2023-08-31 22:39 UTC, mDuo13 commented on docs/README.md
This was `index.md` because of how Redocly generates the URLs / landing pages. I don't think it should be renamed.

2023-08-31 22:39 UTC, mDuo13 commented on docs/SUMMARY.md
> +# Table of contents
This appears to be a machine-generated file, and it's already out of date. If we're going to be procedurally generating content, it should be at build/deploy time so it doesn't have to be separately maintained, and the code to do so should be clearly included in the repo or part of vanilla Redocly, not some unstated external script.

2023-08-31 22:39 UTC, mDuo13 commented on docs/SUMMARY.md
> +  * [Clawback](clawback/clawback-of-issued-currency.md)
Also, I'm not sure if 2-space indentations will work. The Markdown standard is 4 spaces.

2023-08-31 22:39 UTC, mDuo13 commented on docs/clawback/README.md
> +# clawback
Let's not commit stub files like this to the repo.

2023-08-31 22:39 UTC, mDuo13 commented on docs/clawback/clawback-of-issued-currency.md
> +
Why does this change remove the embed?

2023-08-31 22:39 UTC, mDuo13 commented on docs/clawback/clawback-of-issued-currency.md
> +
We intentionally _don't_ leave a blank line between the frontmatter and the h1 at the start of a page.

2023-08-31 22:39 UTC, mDuo13 commented on docs/clawback/clawback-of-issued-currency.md
> +&#x20;For regulatory purposes, some issuers must have the ability to recover issued tokens after they are distributed to accounts. For example, if an issuer were to discover that tokens were sent to
Isn't &#x20; just a space? Also, escaping the asterisks on `*claw back*` is definitely a mistake; that's _supposed_ to be italics there.

2023-10-02 22:46 UTC, oeggert commented
Closing this PR. Hardware requirements added in #65 .

2023-10-02 22:46 UTC, closed without merging